### ISSUE TITLE
We need macs or a mac environment to work on the project.

### ISSUE THREAD

**Issue by jdevans43** [ttu-capstone-podman/podman-installer-mac#8] opened 2019-10-28 13:38 UTC
Acceptance Criteria:
1. Should be able to modify the the machine so we can work.
2. Needs to be cost effective.
3. Should be able to have multiple users with their own environments so we can all work on the project.

**Comment by RothAndrew** [comment] 2019-10-28 13:40
Possible dupe of #7. Take a look and reopen if you believe this is worthy of it's own story.

**Closed as completed** 2019-10-28 13:39 UTC
